In [2]:
from osgeo import gdal
import os
# print(os.getcwd())
# cwd = os.getcwd()
# redband = cwd.join('B4.tif')
in_ds = gdal.Open('Classification_clipraw1.tif')
in_band = in_ds.GetRasterBand(1)
print(in_ds)

<osgeo.gdal.Dataset; proxy of <Swig Object of type 'GDALDatasetShadow *' at 0x00000200BD2BD3F0> >


In [3]:
#numpy array
data = in_band.ReadAsArray()
print(data)

[[18 73 73 ... 48 48 48]
 [73 48 48 ... 48 48 48]
 [48 48 73 ... 73 48 48]
 ...
 [18 73 18 ... 32 32 32]
 [73 73 18 ... 32 32 32]
 [73 18 18 ... 32 32 32]]


In [4]:
#get projection
projection = in_ds.GetProjection()
print(projection)

GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]


In [6]:
#get geotransform
geotransform = in_ds.GetGeoTransform()
geotransform

(83.58509308382706,
 0.00026949458523584514,
 0.0,
 28.265400583292337,
 0.0,
 -0.00026949458523584655)